### PR TITLE
Augment `*_LIBRARY_PATH` on relevant platforms for `ExecutableProduct`s

### PR DESCRIPTION
**Pull request by staticfloat**
When running `check_deps()`, if any dependencies are `ExecutableProduct`s, add Julia's library directory to `LD_LIBRARY_PATH` or `DYLD_LIBRARY_PATH`, as appropriate so that executable products pick up the proper shared libraries

### CODE REVIEW

**Comment by staticfloat** [comment]
@keno The `Ipopt.jl` package has an `ipopt` binary that can't find `libgfortran` on systems where the only `libgfortran` comes from within Julia's `lib/julia` directory.  While we'd normally solve this with `RPATH`'s and such, we can't really do that here because we don't want to have to modify binaries at install time, so I've opted to augment `LD_LIBRARY_PATH` and `DYLD_LIBRARY_PATH` with Julia's `lib/julia` directory so that the binaries (when invoked through e.g. `run()`) can pick them up.

This seems pretty non-controversial to me, but I just want to make sure you agree before releasing this out to the wild.

**Comment by mlubin** [comment]
Copying my comment from https://github.com/JuliaOpt/Ipopt.jl/pull/98#issuecomment-368292651:

> I'd actually prefer for this not to be hidden in check_deps. People are inevitably going to try and use these binaries outside of julia, and putting this code in check_deps would make it one step harder to find out what's going on because check_deps isn't checked into the repository anywhere.

**Comment by staticfloat** [comment]
On the other hand, I think that it’s wrong to force package authors to add 4-5 lines of boilerplate code to each of their packages, and “deps.jl” is the only place where we can insert functionality into the client packages, as one of the requirements of binary builder is that you don’t have to import it in order to get at the binaries it provides.

Perhaps the best solution is to add documentation to BinaryBuilder mentioning this, or do you have a different idea?

**Comment by mlubin** [comment]
Documentation would help resolve my objection. Another option is to provide a specialized version of `setenv` that must be used when running the binaries.
`run(set_binary_env(Ipopt.amplexe)))` is much clearer than having commands hidden in `deps.jl` that modify the environment for the whole julia process.

**Pull request merged**
