### PR TITLE
Correct the extract_platform_key logic to handle FreeBSD

### PR DESCRIPTION
**Pull request by ararslan**

### CODE REVIEW

**Comment by staticfloat** [comment]
Oooh, good catch.  Can you change [these lines](https://github.com/JuliaPackaging/BinaryProvider.jl/blob/3ff1827e2aa8cb2e5b58fa96ad9ed4e630f6df27/test/runtests.jl#L508-L510) as a part of this PR to use `libfoo.x86_64-juliaos-chartreuse.tar.gz` instead?

**Comment by staticfloat** [comment]
Nevermind, we'll just rebase once https://github.com/JuliaPackaging/BinaryProvider.jl/pull/68 is merged

**Comment by ararslan** [comment]
The failures on Julia 0.7 are unrelated (and strange).

**Comment by staticfloat** [comment]
Yep, they are https://github.com/JuliaLang/julia/issues/26904

**Pull request merged**
