### PR TITLE
Import Libdl from stdlib in code run outside the package

### LINKED ISSUE #89: need import Compat.Libdl on 0.7
There seem to be several places that use `Libdl.foo` without first importing the Libdl module, which is required on 0.7.   (For 0.6 compatibility, `import Compat.Libdl`).  For example

* [here](https://github.com/JuliaPackaging/BinaryProvider.jl/blob/865e9ce4e041ea2ef9c841cac5fbc9c1f4eac055/src/Products.jl#L168)
* [here](https://github.com/JuliaPackaging/BinaryProvider.jl/blob/865e9ce4e041ea2ef9c841cac5fbc9c1f4eac055/src/Products.jl#L440)

The latter case is in generated code for `deps.jl` so it triggers deprecation warnings in packages (see e.g. stevengj/Blosc.jl#56).

### PR DESCRIPTION
**Pull request by ararslan**
Fixes #89

### CODE REVIEW

**Comment by stevengj** [comment]
The problem is apparently that `import Libdl` in `deps.jl` conflicts with `using Compat.Libdl` if the calling module has done the latter.   This is a bit frustrating given that they are the same module...

**Comment by stevengj** [comment]
I guess we might use something like
```
if isdefined(@__MODULE__, :Compat)
    import Compat.Libdl
elseif VERSION >= v"...."
    import Libdl
```
but this is still imperfect, since then there will be an error if the caller does `import Compat.Libdl` afterwards.

Alternatively, we could just tell BinaryProvider users not to import `Compat.Libdl`.

The ideal solution would to fix Julia 0.7 so that `import Compat.Libdl; import Libdl` is not an error.

**Comment by ararslan** [comment]
> The ideal solution would to fix Julia 0.7 so that import Compat.Libdl; import Libdl is not an error.

:+1: Any idea how?

Telling people not to use Libdl if they're using BinaryProvider kinda sucks.

**Comment by stevengj** [comment]
The ugly `isdefined(@__MODULE__, :Compat)` workaround seems like it will work for the time being?

**Comment by ararslan** [comment]
Perhaps, though on 0.6, `@__MODULE__` isn't defined unless Compat is defined, so that will require another version check.

**Comment by ararslan** [comment]
```
ERROR: LoadError: LoadError: ArgumentError: Package LibFoo does not have Libdl in its dependencies
```
:man_facepalming:

**Comment by staticfloat** [comment]
I actually think the proper fix here is probably to make `deps.jl` files define their own module.  Then they can import `Libdl` without fear, export the relevant functionality from the module, and be nicely isolated from whatever the calling module is doing.

**Comment by ararslan** [comment]
Seems Pkg3 still doesn't like that we're using Libdl without telling it.

**Comment by staticfloat** [comment]
@StefanKarpinski @KristofferC this is a good point; what’s the easiest way to make sure that everyone that relies upon BinaryProvider gets Libdl made available to them? The fact that BP itself requires Libdl doesn’t mean that the client package can use Libdl, right?

I’m thinking we may want to create wrapper functions for dlopen within BP so that users don’t have to manually add Libdl to all their projects.

**Comment by stevengj** [comment]
Can't we do
```
import BinaryProvider.Libdl
```
assuming JuliaLang/julia#28190 is fixed?

**Comment by stevengj** [comment]
Better yet, just call `BinaryProvider.Libdl.dlopen_e` in the check_deps function.

**Comment by staticfloat** [comment]
> Better yet, just call BinaryProvider.Libdl.dlopen_e in the check_deps function.

You're right, that's clearly the superior choice.  The "BP wrapper function" is just the function itself.  ;)

> This way, we don't introduce a Libdl dependency

Well, `Libdl` is still a dependency of BP, so we're not really saving anything, but I agree that no matter what we do, we shouldn't require the superproject to add `Libdl` to its `Project.toml`.

**Comment by staticfloat** [comment]
So Alex, we don't need to make a submodule anymore, we just need to change all `Libdl.xyz` stuff to be `BinaryProvider.Libdl.xyz`

**Comment by ararslan** [comment]
Welp, seems that doesn't work either. :neutral_face:

**Comment by staticfloat** [comment]
Oh, right, doy.  We want `deps.jl` files to be able to eschew loading `BinaryProvider` at runtime.  Huh.  Okay then, this is kind of a problem.  I'm not seeing a way out of this that doesn't involve us requiring all users to manually add `Libdl` to their projects.

**Comment by KristofferC** [comment]
If a package depend on `BinaryProvider` then it can load it so why can't it use `BinaryProvider.Libdl`?

**Comment by staticfloat** [comment]
To avoid increasing package load time, we try not to force all packages to `using BinaryProvider` except when running `Pkg.build("Package")`.  The only thing we need to do at runtime (after we've already built in a previous session) is to `dlopen()`; all the special stuff in `BinaryProvider` is unneeded at runtime, so we try to avoid having it be loaded.

**Comment by ararslan** [comment]
FWIW in the code that generates the General registry from METADATA, there's explicit logic to inject a dependency on Libdl into the package's TOML files if a dependency on BinDeps is declared. Perhaps we should be doing something similar here? Though I guess that won't help with the test here, or with manually specified Project files...

**Comment by staticfloat** [comment]
I guess we could do that....

For this test case we just need to add `Libdl` ourselves to the `Project.toml`.  That's easy enough.

**Pull request merged**
