### PR TITLE
Respect isolation of `locate` in `write_deps`

### PR DESCRIPTION
**Pull request by giordano**
This pull request is merging `master` branch up to version v0.5.5 into the `rollback` branch, and then is fixing a call to `locate` in `write_deps` to respect the value of `isolate`.  Spotted while trying to debug https://github.com/JuliaOpt/CSDP.jl/pull/56

### CODE REVIEW

**Comment by staticfloat** [comment]
Once we do this, let's just hard-reset `master` to be the same as `rollback` so we can avoid this git history nonsense.

**Comment by staticfloat** [comment]
@ararslan do you have any idea what's going on with the FreeBSD stuff here?  Should we just turn it off?

**Comment by giordano** [comment]
Yes, Cirrus has been having a very bad time.  Travis is more reliable for FreeBSD

**Comment by ararslan** [comment]
Yeah I think it's something wonky with the image that Cirrus is using; I think it needs a system update or something. `os: freebsd` on Travis should work.

**Comment by giordano** [comment]
>  let's just hard-reset master to be the same as rollback

Note I didn't merge https://github.com/JuliaPackaging/BinaryProvider.jl/commit/6779f5408a5ec0047ed581a3ffa02edcf044be00 in here, as it would have caused a conflict.  Would a hard-reset cause problems to Pkg if that revision completely disappear?

**Comment by staticfloat** [comment]
It won't disappear; github will keep those old commits around.  If we want to be paranoid, let's just create another branch holding that history called `temporal_anomaly` or `those_darn_tachyons` or something.

**Review by staticfloat — APPROVED** [review]

**Comment by ViralBShah** [comment]
I imagine that if this works, it could be useful for many other packages.

**Pull request merged**
