### PR TITLE
explicitly specify 7z

### PR DESCRIPTION
**Pull request by musm**

### CODE REVIEW

**Comment by musm** [comment]
https://github.com/JuliaLang/julia/pull/21540

**Comment by musm** [comment]
cc @staticfloat

**Comment by musm** [comment]
@SimonDanisch

**Comment by staticfloat** [comment]
Hey @musm, thanks for the contribution here.  May I ask what you're intending to do with this codebase?  I have a [PR open](https://github.com/JuliaPackaging/BinaryProvider.jl/pull/1) that is basically my scratch space where I'm sketching out what I think the package should look like (and I will incorporate this change within it) but it's still not certain exactly how this will go down.

**Comment by musm** [comment]
Hi @staticfloat  I don't have any plans. I wanted to get the julia PR that removes the default of adding the julia path to the .juliarc file on Windows as like linux merged and thus packages that need 7z just need to make sure they include  the correct.

Should've checked that this package is registered first.

**Pull request closed without merging**
