### PR TITLE
Precompile for speed

### PR DESCRIPTION
**Pull request by staticfloat**
Also increase relocatability

### CODE REVIEW

**Comment by KristofferC** [comment]
I have never seen `precompile` give any speed benefit except if used in combination with sysimg building. Do you have any numbers here or is the purpose actually to make BP faster when used in sysimgs?

**Comment by KristofferC** [comment]
Also not that you are including all anonymous functions here, so as soon as you make a change in a closure or something, this will likely break since the symbol will be gone.

**Comment by staticfloat** [comment]
Yeah, I figured that this would break as soon as someone breathes on the
codebase.  But that doesn’t particularly annoy me; it’s easy to regenerate
the file.

I measure about 50ms of speedup (So that’s a 10% overall speedup).  It
looks like the `__init__()` function spends that time compiling itself and
e.g. `probe_platform_engines()`.  With this change, there’s essentially no
compilation done at all during startup, it’s all just 400ms spent reading
serialized code in from disk.
-E


On October 6, 2018 at 10:48:07 PM, Kristoffer Carlsson (
notifications@github.com) wrote:

Also not that you are including all anonymous functions here, so as soon as
you make a change in a closure or something, this will likely break since
the symbol will be gone.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/JuliaPackaging/BinaryProvider.jl/pull/126#issuecomment-427579373>,
or mute the thread

**Comment by staticfloat** [comment]
Welp, that didn't take long to get annoying.  :P  I removed everything that had a name starting with `#`.

**Comment by KristofferC** [comment]
You could always just generate it for a release.

**Comment by staticfloat** [comment]
Yes, well another annoyance is that some anonymous functions don't exist on some platforms, so the `precompile.jl` file has to be the intersection of snoop runs on all different platforms.  :/

It's okay, with these few lines I already get most of the benefit, so no biggie.

**Pull request merged**
